# Generated by Django 5.0 on 2024-07-13 13:41

from django.db import migrations, models

import generic.storages


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_new_description_en_new_description_ru_new_link_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='image',
            field=models.ImageField(storage=generic.storages.OverWriteStorage(), upload_to='news/'),
        ),
    ]
