# Generated by Django 5.0 on 2024-07-13 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_new_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='new',
            options={'ordering': ('-pub_date',)},
        ),
    ]
