# Generated by Django 5.0 on 2024-07-14 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-created_at', '-modified_at')},
        ),
    ]
