# Generated by Django 5.0 on 2024-07-16 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_new_viewers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='new',
            options={'ordering': ('-publicated_at',)},
        ),
        migrations.RenameField(
            model_name='new',
            old_name='pub_date',
            new_name='publicated_at',
        ),
    ]
