# Generated by Django 5.0 on 2024-02-16 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_wn8'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hits_percent',
        ),
    ]
