# Generated by Django 5.0 on 2024-02-16 22:40

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_user_hits_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hits_percent',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('hits'), '*', models.Value(100)), '/', models.F('shots')), output_field=models.FloatField()),
        ),
    ]
