# Generated by Django 5.0 on 2024-02-21 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_hits_percent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-created_at', '-modified_at')},
        ),
    ]
