# Generated by Django 5.0 on 2024-05-07 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_user_role'),
        ('directory', '0020_auto_20240508_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='directory.role'),
        ),
    ]
