# Generated by Django 5.0.7 on 2024-09-10 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_role_fk_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hits_percent',
        ),
        migrations.RemoveField(
            model_name='user',
            name='wins_percent',
        ),
    ]
