# Generated by Django 5.0.7 on 2024-09-10 08:12

import django.db.models.expressions
import django.db.models.functions.comparison
import django.db.models.functions.math
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_user_hits_percent_remove_user_wins_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hits_percent',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.math.Round(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.functions.comparison.Cast(models.F('hits'), models.FloatField()), '*', models.Value(100.0)), '/', django.db.models.functions.comparison.Cast(models.F('shots'), models.FloatField())), precision=2), output_field=models.FloatField()),
        ),
        migrations.AddField(
            model_name='user',
            name='wins_percent',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.math.Round(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.functions.comparison.Cast(models.F('wins'), models.FloatField()), '*', models.Value(100.0)), '/', django.db.models.functions.comparison.Cast(models.F('battles'), models.FloatField())), precision=2), output_field=models.FloatField()),
        ),
    ]
