# Generated by Django 5.0 on 2024-01-29 16:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.IntegerField(unique=True)),
                ('tag', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=128)),
                ('motto', models.TextField()),
                ('color', models.CharField(max_length=7)),
                ('emblem', models.URLField()),
            ],
            options={
                'ordering': ['-created_at', '-modified_at'],
                'abstract': False,
            },
        ),
    ]
