# Generated by Django 5.0 on 2024-02-03 01:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clan', '0002_stronghold_build_and_more'),
        ('directory', '0008_auto_20240203_0037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('level', models.PositiveSmallIntegerField()),
                ('count', models.PositiveSmallIntegerField()),
                ('clan_bonus', models.FloatField(null=True)),
                ('random_bonus', models.FloatField(null=True)),
                ('activated_at', models.DateTimeField(null=True)),
                ('active_till', models.DateTimeField(null=True)),
                ('disposable', models.BooleanField(default=False, help_text='Является ли резерв резервом для сражений')),
                ('ready_to_activate', models.BooleanField(default=False)),
                ('x_level_only', models.BooleanField(default=False)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserves', to='directory.reservetype')),
            ],
            options={
                'ordering': ['type', 'level'],
            },
        ),
        migrations.AddConstraint(
            model_name='reserve',
            constraint=models.UniqueConstraint(fields=('type', 'level'), name='type and level unique constraint'),
        ),
    ]
