# Generated by Django 5.0 on 2024-02-03 16:21

from django.db import migrations, models

import generic.storages


class Migration(migrations.Migration):

    dependencies = [
        ('clan', '0003_reserve_reserve_type_and_level_unique_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clan',
            name='emblem',
            field=models.ImageField(storage=generic.storages.OverWriteStorage(), upload_to='clan/'),
        ),
    ]
