# Generated by Django 5.0 on 2024-05-06 19:18

from django.db import migrations


def add_types_to_builds(apps, schema_editor):
    Build = apps.get_model('clan.Build')
    StrongholdBuildType = apps.get_model('directory.StrongholdBuildType')

    types = dict(StrongholdBuildType.objects.values_list('name', 'id'))
    builds = Build.objects.all()

    for build in builds:
        build.type_id = types[build.title]
        build.save(update_fields=['type_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('clan', '0006_build_type'),
    ]

    operations = [
        migrations.RunPython(add_types_to_builds, reverse_code=migrations.RunPython.noop),
    ]
