# Generated by Django 5.0 on 2024-05-06 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clan', '0007_auto_20240506_2218'),
        ('directory', '0015_auto_20240506_2208'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='build',
            name='stronghold and title unique constraint',
        ),
        migrations.RemoveField(
            model_name='build',
            name='title',
        ),
        migrations.AlterField(
            model_name='build',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='directory.strongholdbuildtype'),
        ),
        migrations.AddConstraint(
            model_name='build',
            constraint=models.UniqueConstraint(fields=('stronghold', 'type'), name='stronghold and type unique constraint'),
        ),
    ]
