# Generated by Django 5.0 on 2024-07-07 21:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import cluster.middlewares


class Migration(migrations.Migration):

    dependencies = [
        ('clan', '0008_remove_build_stronghold_and_title_unique_constraint_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReserveScheduler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('day', models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('time', models.TimeField()),
                ('author', models.ForeignKey(default=cluster.middlewares.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('reserve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedulers', to='clan.reserve')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
