# Generated by Django 5.0 on 2024-07-07 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clan', '0009_reservescheduler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservescheduler',
            name='reserve',
            field=models.ForeignKey(limit_choices_to={'disposable': False}, on_delete=django.db.models.deletion.CASCADE, related_name='schedulers', to='clan.reserve'),
        ),
    ]
