# Generated by Django 5.0 on 2024-07-08 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clan', '0010_alter_reservescheduler_reserve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservescheduler',
            name='day',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')]),
        ),
    ]
