# Generated by Django 5.0 on 2024-01-29 16:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GunMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('mark_20', models.IntegerField()),
                ('mark_30', models.IntegerField()),
                ('mark_40', models.IntegerField()),
                ('mark_50', models.IntegerField()),
                ('mark_55', models.IntegerField()),
                ('mark_60', models.IntegerField()),
                ('mark_65', models.IntegerField()),
                ('mark_70', models.IntegerField()),
                ('mark_75', models.IntegerField()),
                ('mark_80', models.IntegerField()),
                ('mark_85', models.IntegerField()),
                ('mark_90', models.IntegerField()),
                ('mark_95', models.IntegerField()),
                ('mark_100', models.IntegerField()),
                ('tank', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gun_mark', to='directory.tank')),
            ],
            options={
                'ordering': ['-created_at', '-modified_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('class_3', models.IntegerField()),
                ('class_2', models.IntegerField()),
                ('class_1', models.IntegerField()),
                ('master', models.IntegerField()),
                ('tank', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mastery', to='directory.tank')),
            ],
            options={
                'ordering': ['-created_at', '-modified_at'],
                'abstract': False,
            },
        ),
    ]
