# Generated by Django 5.0 on 2024-02-03 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gunmark',
            name='mark_100',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='gunmark',
            name='mark_20',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='gunmark',
            name='mark_30',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='gunmark',
            name='mark_40',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='gunmark',
            name='mark_50',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='gunmark',
            name='mark_55',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='gunmark',
            name='mark_60',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='gunmark',
            name='mark_65',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='gunmark',
            name='mark_70',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='gunmark',
            name='mark_75',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='gunmark',
            name='mark_80',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='gunmark',
            name='mark_85',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='gunmark',
            name='mark_90',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='gunmark',
            name='mark_95',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='mastery',
            name='class_1',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='mastery',
            name='class_2',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='mastery',
            name='class_3',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='mastery',
            name='master',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
