# Generated by Django 5.0 on 2024-02-21 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0002_alter_gunmark_mark_100_alter_gunmark_mark_20_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gunmark',
            options={'ordering': ('-created_at', '-modified_at')},
        ),
        migrations.AlterModelOptions(
            name='mastery',
            options={'ordering': ('-created_at', '-modified_at')},
        ),
    ]
