# Generated by Django 5.0 on 2024-02-10 23:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tactic', '0004_room_users_alter_userroomrelation_room_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userroomrelation',
            options={},
        ),
        migrations.AddConstraint(
            model_name='userroomrelation',
            constraint=models.UniqueConstraint(fields=('room', 'user'), name='room and user unique together'),
        ),
    ]
