# Generated by Django 5.0 on 2024-02-11 20:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tactic', '0005_alter_userroomrelation_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userroomrelation',
            name='room and user unique together',
        ),
        migrations.AddConstraint(
            model_name='userroomrelation',
            constraint=models.UniqueConstraint(fields=('room', 'user'), name='room and user unique together', violation_error_code=1),
        ),
    ]
