# Generated by Django 5.0 on 2023-12-30 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('level', models.IntegerField()),
                ('type', models.CharField(choices=[('SPG', 'САУ'), ('AT-SPG', 'ПТ-САУ'), ('lightTank', 'Легкий танк'), ('mediumTank', 'Средний танк'), ('heavyTank', 'Тяжелый танк')], max_length=10)),
                ('nation', models.CharField(choices=[('ussr', 'СССР'), ('germany', 'Германия'), ('usa', 'США'), ('uk', 'Великобритания'), ('france', 'Франция'), ('italy', 'Италия'), ('china', 'Китай'), ('japan', 'Япония'), ('poland', 'Польша'), ('sweden', 'Швеция'), ('czech', 'Чехословакия')], max_length=7)),
                ('tank_id', models.IntegerField(unique=True)),
            ],
        ),
    ]
