# Generated by Django 5.0 on 2024-01-29 16:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=256)),
                ('level', models.IntegerField()),
                ('type', models.CharField(choices=[('SPG', 'САУ'), ('AT-SPG', 'ПТ-САУ'), ('lightTank', 'Легкий танк'), ('mediumTank', 'Средний танк'), ('heavyTank', 'Тяжелый танк')], max_length=10)),
                ('nation', models.CharField(choices=[('ussr', 'СССР'), ('germany', 'Германия'), ('usa', 'США'), ('uk', 'Великобритания'), ('france', 'Франция'), ('italy', 'Италия'), ('china', 'Китай'), ('japan', 'Япония'), ('poland', 'Польша'), ('sweden', 'Швеция'), ('czech', 'Чехословакия')], max_length=7)),
                ('contour', models.URLField()),
            ],
            options={
                'ordering': ['-created_at', '-modified_at'],
                'abstract': False,
            },
        ),
    ]
