# Generated by Django 5.0 on 2023-12-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_clan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('role', models.IntegerField()),
                ('account_id', models.IntegerField(unique=True)),
            ],
        ),
    ]
