# Generated by Django 5.0 on 2024-02-02 19:37

from django.core.management import call_command
from django.db import migrations


def load_maps(apps, schema_editor):
    call_command('load_maps', files_update=True)


class Migration(migrations.Migration):
    dependencies = [
        ('directory', '0003_map'),
    ]

    operations = [
        migrations.RunPython(load_maps, reverse_code=migrations.RunPython.noop),
    ]
