# Generated by Django 5.0 on 2024-02-02 20:48

from django.db import migrations, models

import generic.storages


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0004_auto_20240202_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='file',
            field=models.ImageField(storage=generic.storages.OverWriteStorage(), upload_to='maps/'),
        ),
    ]
