# Generated by Django 5.0 on 2024-02-02 20:52

from django.db import migrations, models

import generic.storages


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0005_alter_map_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tank',
            name='contour',
            field=models.ImageField(storage=generic.storages.OverWriteStorage(), upload_to='tanks/'),
        ),
    ]
