# Generated by Django 5.0 on 2024-02-02 22:37

from django.db import migrations, models

import generic.storages


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0006_alter_tank_contour'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReserveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('file', models.ImageField(storage=generic.storages.OverWriteStorage(), upload_to='reserve_types/')),
                ('external_id', models.CharField(choices=[('BATTLE_PAYMENTS', 'Боевые выплаты'), ('TACTICAL_TRAINING', 'Тактическая подготовка'), ('MILITARY_MANEUVERS', 'Военные учения'), ('ADDITIONAL_BRIEFING', 'Дополнительный инструктаж'), ('HIGH_CAPACITY_TRANSPORT', 'Большегрузный транспорт'), ('REQUISITION', 'Реквизиция'), ('ARTILLERY_STRIKE', 'Артобстрел'), ('INSPIRATION', 'Воодушевление')], max_length=32, unique=True)),
            ],
        ),
    ]
