# Generated by Django 5.0 on 2024-02-07 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0008_auto_20240203_0037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='map',
            options={'ordering': ['name']},
        ),
    ]
