# Generated by Django 5.0 on 2024-02-21 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0009_alter_map_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tank',
            options={'ordering': ('-created_at', '-modified_at')},
        ),
    ]
