# Generated by Django 5.0 on 2024-03-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0010_alter_tank_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tank',
            name='external_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
