# Generated by Django 5.0 on 2024-05-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0011_alter_tank_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tank',
            name='name_en',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='tank',
            name='name_ru',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
