# Generated by Django 5.0 on 2024-05-06 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0012_tank_name_en_tank_name_ru'),
    ]

    operations = [
        migrations.CreateModel(
            name='StrongholdBuildType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('external_id', models.CharField(choices=[('Financial Unit', 'Financial Unit'), ('Tankodrome', 'Tankodrome'), ('Military School', 'Military School'), ('Training Unit', 'Training Unit'), ('Transportation Unit', 'Transportation Unit'), ('Trophy Brigade', 'Trophy Brigade'), ('Artillery Battalion', 'Artillery Battalion'), ('Logistical Service', 'Logistical Service')], max_length=32, unique=True)),
            ],
        ),
    ]
