# Generated by Django 5.0 on 2024-05-06 19:08

from django.db import migrations

from apps.directory.models import StrongholdBuildType


def create_build_types(apps, schema_editor):
    StrongholdBuildTypeModel = apps.get_model('directory.StrongholdBuildType')
    builds_data = [
        {
            'external_id': StrongholdBuildType.ExternalID.FINANCIAL_UNIT,
            'name': 'Financial Unit',
            'name_en': 'Financial Unit',
            'name_ru': 'Финансовая часть',
        },
        {
            'external_id': StrongholdBuildType.ExternalID.TANKODROME,
            'name': 'Tankodrome',
            'name_en': 'Tankodrome',
            'name_ru': 'Танкодром',
        },
        {
            'external_id': StrongholdBuildType.ExternalID.MILITARY_SCHOOL,
            'name': 'Military School',
            'name_en': 'Military School',
            'name_ru': 'Военное училище',
        },
        {
            'external_id': StrongholdBuildType.ExternalID.TRAINING_UNIT,
            'name': 'Training Unit',
            'name_en': 'Training Unit',
            'name_ru': 'Учебная часть',
        },
        {
            'external_id': StrongholdBuildType.ExternalID.TRANSPORTATION_UNIT,
            'name': 'Transportation Unit',
            'name_en': 'Transportation Unit',
            'name_ru': 'Автотранспортная часть',
        },
        {
            'external_id': StrongholdBuildType.ExternalID.TROPHY_BRIGADE,
            'name': 'Trophy Brigade',
            'name_en': 'Trophy Brigade',
            'name_ru': 'Трофейная бригата',
        },
        {
            'external_id': StrongholdBuildType.ExternalID.ARTILLERY_BATTALION,
            'name': 'Artillery Battalion',
            'name_en': 'Artillery Battalion',
            'name_ru': 'Артиллерийский дивизион',
        },
        {
            'external_id': StrongholdBuildType.ExternalID.LOGISTICAL_SERVICE,
            'name': 'Logistical Service',
            'name_en': 'Logistical Service',
            'name_ru': 'Служба тыла',
        },
    ]
    builds = []

    for build in builds_data:
        builds.append(StrongholdBuildTypeModel(**build))

    StrongholdBuildTypeModel.objects.bulk_create(builds)


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0014_strongholdbuildtype_name_en_and_more'),
    ]

    operations = [
        migrations.RunPython(create_build_types, reverse_code=migrations.RunPython.noop),
    ]
