# Generated by Django 5.0 on 2024-05-06 19:08

from django.db import migrations

from apps.directory.models import StrongholdBuildType


def create_build_types(apps, schema_editor):
    from apps.directory.services.stronghold import StrongholdBuildTypeService
    StrongholdBuildTypeService.update_build_types()


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0014_strongholdbuildtype_name_en_and_more'),
    ]

    operations = [
        migrations.RunPython(create_build_types, reverse_code=migrations.RunPython.noop),
    ]
