# Generated by Django 5.0 on 2024-05-07 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0015_auto_20240506_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservetype',
            name='name_en',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='reservetype',
            name='name_ru',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='reservetype',
            name='external_id',
            field=models.CharField(choices=[('BATTLE_PAYMENTS', 'Battle Payments'), ('TACTICAL_TRAINING', 'Tactical Training'), ('MILITARY_MANEUVERS', 'Military Maneuvers'), ('ADDITIONAL_BRIEFING', 'Additional Briefing'), ('HIGH_CAPACITY_TRANSPORT', 'High Capacity Transport'), ('REQUISITION', 'Requisition'), ('ARTILLERY_STRIKE', 'Artillery Strike'), ('INSPIRATION', 'Inspiration')], max_length=32, unique=True),
        ),
    ]
