# Generated by Django 5.0 on 2024-05-07 20:36

from django.db import migrations


def update_reserve_types(apps, schema_editor):
    from apps.directory.services.reserve_types import ReserveTypeService
    ReserveTypeService.update_reserve_types()


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0016_reservetype_name_en_reservetype_name_ru_and_more'),
    ]

    operations = [
        migrations.RunPython(update_reserve_types, reverse_code=migrations.RunPython.noop),
    ]
