# Generated by Django 5.0 on 2024-05-07 21:43

from django.db import migrations


def update_roles(apps, schema_editor):
    from apps.directory.services.clan import RoleService
    RoleService.update_roles()


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0019_role_name_en_role_name_ru'),
    ]

    operations = [
        migrations.RunPython(update_roles, reverse_code=migrations.RunPython.noop),
    ]
