# Generated by Django 5.0 on 2024-05-08 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0020_auto_20240508_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='name_en',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='map',
            name='name_ru',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='external_id',
            field=models.CharField(choices=[('commander', 'Commander'), ('executive_officer', 'Executive Officer'), ('personnel_officer', 'Personnel Officer'), ('combat_officer', 'Combat Officer'), ('intelligence_officer', 'Intelligence Officer'), ('quartermaster', 'Quartermaster'), ('recruitment_officer', 'Recruitment Officer'), ('junior_officer', 'Junior Officer'), ('private', 'Private'), ('recruit', 'Recruit'), ('reservist', 'Reservist')], max_length=32, unique=True),
        ),
    ]
