# Generated by Django 5.0 on 2024-05-08 20:23

from django.db import migrations


def update_maps(apps, schema_editor):
    from apps.directory.services.maps import MapService
    MapService.update_maps()


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0021_map_name_en_map_name_ru_alter_role_external_id'),
    ]

    operations = [
        migrations.RunPython(update_maps, reverse_code=migrations.RunPython.noop),
    ]
