# Generated by Django 5.0 on 2024-03-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='external_id',
            field=models.BigIntegerField(unique=True),
        ),
    ]
