# Generated by Django 3.1.6 on 2021-03-12 02:48

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_name', models.TextField(verbose_name='Название статьи')),
                ('article_text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текст статьи')),
                ('article_date', models.DateTimeField(verbose_name='Дата публикации')),
                ('article_publicate', models.BooleanField(default=False, verbose_name='Опубликовать?')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.CreateModel(
            name='ClanId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.TextField(default=1, verbose_name='ID клана')),
            ],
            options={
                'verbose_name': 'ID клана',
                'verbose_name_plural': 'ID клана',
            },
        ),
        migrations.CreateModel(
            name='ClanInfo',
            fields=[
                ('clan_tag', models.TextField(default='Tag', primary_key=True, serialize=False, verbose_name='Тэг клана')),
                ('clan_name', models.TextField(default='Name', null=True, verbose_name='Название клана')),
                ('clan_motto', models.TextField(default='Motto', null=True, verbose_name='Девиз клана')),
                ('clan_color', models.TextField(default='#fff', null=True, verbose_name='Цвет клана')),
                ('clan_emblem', models.TextField(default=0, null=True, verbose_name='Эмблема клана')),
            ],
            options={
                'verbose_name': 'Информация о клане',
                'verbose_name_plural': 'Информация о клане',
            },
        ),
        migrations.CreateModel(
            name='ClanRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clan_role_ru', models.TextField(null=True, verbose_name='Должность игрока')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('player_id', models.TextField(primary_key=True, serialize=False, verbose_name='ID игрока')),
                ('player_name', models.TextField(null=True, verbose_name='Имя игрока')),
                ('player_battles', models.TextField(default=0, null=True, verbose_name='Всего боев')),
                ('player_wgr', models.TextField(default=0, null=True, verbose_name='WGR')),
                ('player_win', models.TextField(default=0, null=True, verbose_name='Всего побед')),
                ('player_damage', models.TextField(default=0, null=True, verbose_name='Всего дамага')),
                ('player_frags', models.TextField(default=0, null=True, verbose_name='Всего фрагов')),
                ('player_clan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.clanid')),
                ('player_role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.clanrole')),
            ],
            options={
                'verbose_name': 'Игрок клана',
                'verbose_name_plural': 'Игроки клана',
                'ordering': ('player_role_id',),
            },
        ),
        migrations.CreateModel(
            name='ClanStatic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clan_sh10', models.TextField(default=0, null=True, verbose_name='УРЭЛО 10')),
                ('clan_sh8', models.TextField(default=0, null=True, verbose_name='УРЭЛО 8')),
                ('clan_sh6', models.TextField(default=0, null=True, verbose_name='УРЭЛО 6')),
                ('clan_gm10', models.TextField(default=0, null=True, verbose_name='ГКЭЛО 10')),
                ('clan_gm8', models.TextField(default=0, null=True, verbose_name='ГКЭЛО 8')),
                ('clan_gm6', models.TextField(default=0, null=True, verbose_name='ГКЭЛО 6')),
                ('clan_battles_count', models.TextField(default=0, null=True, verbose_name='Среднее кол-во боев')),
                ('clan_win_rate', models.TextField(default=0, null=True, verbose_name='Среднее процент побед')),
                ('clan_rate', models.TextField(default=0, null=True, verbose_name='Рейтинг клана')),
                ('clan_position', models.TextField(default=0, null=True, verbose_name='Позиция клана')),
                ('clan_xp_per_battle', models.TextField(default=0, null=True, verbose_name='Средний опыт за бой')),
                ('clan_damage_per_battle', models.TextField(default=0, null=True, verbose_name='Средний урон за бой')),
                ('clan_static_update', models.DateTimeField(auto_now=True, verbose_name='Время обновления статистики')),
                ('clan_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.claninfo')),
            ],
            options={
                'verbose_name': 'Статистика клане',
                'verbose_name_plural': 'Статистика клане',
            },
        ),
    ]
