# Generated by Django 3.1.6 on 2021-02-05 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClanId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_id', models.TextField(verbose_name='ID клана')),
            ],
            options={
                'verbose_name': 'ID клана',
                'verbose_name_plural': 'ID клана',
            },
        ),
        migrations.CreateModel(
            name='ClanName',
            fields=[
                ('clan_name', models.TextField(primary_key=True, serialize=False, verbose_name='Название клана')),
                ('clan_motto', models.TextField(null=True, verbose_name='Девиз клана')),
            ],
            options={
                'verbose_name': 'Название и девиз клана',
                'verbose_name_plural': 'Название и девиз клана',
            },
        ),
        migrations.CreateModel(
            name='ClanRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clan_role_ru', models.TextField(null=True, verbose_name='Должность игрока')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('player_id', models.TextField(primary_key=True, serialize=False, verbose_name='ID игрока')),
                ('player_name', models.TextField(verbose_name='Имя игрока')),
                ('player_clan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.clanid')),
                ('player_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.clanrole')),
            ],
            options={
                'verbose_name': 'Игрок клана',
                'verbose_name_plural': 'Игроки клана',
            },
        ),
    ]
