# Generated by Django 3.1.6 on 2021-02-09 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clanrole',
            options={'ordering': ('id',), 'verbose_name': 'Должность', 'verbose_name_plural': 'Должности'},
        ),
        migrations.AlterModelOptions(
            name='players',
            options={'ordering': ('player_role_id',), 'verbose_name': 'Игрок клана', 'verbose_name_plural': 'Игроки клана'},
        ),
        migrations.AddField(
            model_name='players',
            name='player_battles',
            field=models.TextField(default=0, verbose_name='Всего боев'),
        ),
        migrations.AddField(
            model_name='players',
            name='player_damage',
            field=models.TextField(default=0, verbose_name='Всего дамага'),
        ),
        migrations.AddField(
            model_name='players',
            name='player_frags',
            field=models.TextField(default=0, verbose_name='Всего фрагов'),
        ),
        migrations.AddField(
            model_name='players',
            name='player_wgr',
            field=models.TextField(default=0, verbose_name='WGR'),
        ),
        migrations.AddField(
            model_name='players',
            name='player_win',
            field=models.TextField(default=0, verbose_name='Всего побед'),
        ),
    ]
