# Generated by Django 3.1.6 on 2021-02-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210210_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clanid',
            name='_id',
            field=models.TextField(default=1, verbose_name='ID клана'),
        ),
        migrations.AlterField(
            model_name='clanname',
            name='clan_motto',
            field=models.TextField(default='Motto', null=True, verbose_name='Девиз клана'),
        ),
        migrations.AlterField(
            model_name='clanname',
            name='clan_name',
            field=models.TextField(default='Name', primary_key=True, serialize=False, verbose_name='Название клана'),
        ),
    ]
