# Generated by Django 3.1.6 on 2021-02-10 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210210_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='clanname',
            name='clan_battles_count',
            field=models.TextField(default=0, null=True, verbose_name='Среднее кол-во боев'),
        ),
        migrations.AddField(
            model_name='clanname',
            name='clan_damage_per_battle',
            field=models.TextField(default=0, null=True, verbose_name='Средний урон за бой'),
        ),
        migrations.AddField(
            model_name='clanname',
            name='clan_gm10',
            field=models.TextField(default=0, null=True, verbose_name='ГКЭЛО 10'),
        ),
        migrations.AddField(
            model_name='clanname',
            name='clan_gm6',
            field=models.TextField(default=0, null=True, verbose_name='ГКЭЛО 6'),
        ),
        migrations.AddField(
            model_name='clanname',
            name='clan_gm8',
            field=models.TextField(default=0, null=True, verbose_name='ГКЭЛО 8'),
        ),
        migrations.AddField(
            model_name='clanname',
            name='clan_position',
            field=models.TextField(default=0, null=True, verbose_name='Позиция клана'),
        ),
        migrations.AddField(
            model_name='clanname',
            name='clan_rate',
            field=models.TextField(default=0, null=True, verbose_name='Рейтинг клана'),
        ),
        migrations.AddField(
            model_name='clanname',
            name='clan_sh10',
            field=models.TextField(default=0, null=True, verbose_name='УРЭЛО 10'),
        ),
        migrations.AddField(
            model_name='clanname',
            name='clan_sh6',
            field=models.TextField(default=0, null=True, verbose_name='УРЭЛО 6'),
        ),
        migrations.AddField(
            model_name='clanname',
            name='clan_sh8',
            field=models.TextField(default=0, null=True, verbose_name='УРЭЛО 8'),
        ),
        migrations.AddField(
            model_name='clanname',
            name='clan_win_rate',
            field=models.TextField(default=0, null=True, verbose_name='Среднее процент побед'),
        ),
        migrations.AddField(
            model_name='clanname',
            name='clan_xp_per_battle',
            field=models.TextField(default=0, null=True, verbose_name='Средний опыт за бой'),
        ),
    ]
