# Generated by Django 3.1.6 on 2021-02-10 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210210_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_name', models.TextField(verbose_name='Название статьи')),
                ('article_text', models.TextField(verbose_name='Текст статьи')),
                ('article_date', models.DateTimeField(auto_now=True, verbose_name='Дата публикации')),
                ('article_publicate', models.BooleanField(default=False, verbose_name='Опубликовать?')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
        migrations.AlterModelOptions(
            name='clanname',
            options={'verbose_name': 'Статистика клана', 'verbose_name_plural': 'Статистика клана'},
        ),
    ]
