# Generated by Django 3.1.6 on 2021-02-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210211_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='clanname',
            name='clan_tag',
            field=models.TextField(default='Tag', primary_key=True, serialize=False, verbose_name='Тэг клана'),
        ),
        migrations.AlterField(
            model_name='clanname',
            name='clan_name',
            field=models.TextField(default='Name', null=True, verbose_name='Название клана'),
        ),
    ]
