# Generated by Django 3.1.6 on 2021-02-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210215_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='clanname',
            name='clan_color',
            field=models.TextField(default='#fff', null=True, verbose_name='Цвет клана'),
        ),
    ]
