# Generated by Django 3.1.6 on 2021-02-17 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_clanname_clan_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='clanname',
            name='clan_emblem',
            field=models.TextField(null=True, verbose_name='Эмблема клана'),
        ),
    ]
