# Generated by Django 3.1.6 on 2021-02-17 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_clanname_clan_emblem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clanname',
            name='clan_emblem',
            field=models.TextField(default=0, null=True, verbose_name='Эмблема клана'),
        ),
    ]
