# Generated by Django 3.1.6 on 2021-02-17 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210217_0434'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClanInfo',
            fields=[
                ('clan_tag', models.TextField(default='Tag', primary_key=True, serialize=False, verbose_name='Тэг клана')),
                ('clan_name', models.TextField(default='Name', null=True, verbose_name='Название клана')),
                ('clan_motto', models.TextField(default='Motto', null=True, verbose_name='Девиз клана')),
                ('clan_color', models.TextField(default='#fff', null=True, verbose_name='Цвет клана')),
                ('clan_emblem', models.TextField(default=0, null=True, verbose_name='Эмблема клана')),
            ],
            options={
                'verbose_name': 'Информация о клане',
                'verbose_name_plural': 'Информация о клане',
            },
        ),
        migrations.CreateModel(
            name='ClanStatic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clan_sh10', models.TextField(default=0, null=True, verbose_name='УРЭЛО 10')),
                ('clan_sh8', models.TextField(default=0, null=True, verbose_name='УРЭЛО 8')),
                ('clan_sh6', models.TextField(default=0, null=True, verbose_name='УРЭЛО 6')),
                ('clan_gm10', models.TextField(default=0, null=True, verbose_name='ГКЭЛО 10')),
                ('clan_gm8', models.TextField(default=0, null=True, verbose_name='ГКЭЛО 8')),
                ('clan_gm6', models.TextField(default=0, null=True, verbose_name='ГКЭЛО 6')),
                ('clan_battles_count', models.TextField(default=0, null=True, verbose_name='Среднее кол-во боев')),
                ('clan_win_rate', models.TextField(default=0, null=True, verbose_name='Среднее процент побед')),
                ('clan_rate', models.TextField(default=0, null=True, verbose_name='Рейтинг клана')),
                ('clan_position', models.TextField(default=0, null=True, verbose_name='Позиция клана')),
                ('clan_xp_per_battle', models.TextField(default=0, null=True, verbose_name='Средний опыт за бой')),
                ('clan_damage_per_battle', models.TextField(default=0, null=True, verbose_name='Средний урон за бой')),
            ],
            options={
                'verbose_name': 'Статистика клане',
                'verbose_name_plural': 'Статистика клане',
            },
        ),
        migrations.DeleteModel(
            name='ClanName',
        ),
    ]
