# Generated by Django 3.1.6 on 2021-02-17 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210217_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='clanstatic',
            name='clan_static_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Время обновления статистики'),
        ),
    ]
