# Generated by Django 3.1.6 on 2021-02-17 15:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_clanstatic_clan_static_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='clanstatic',
            name='clan_tag',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='main.claninfo'),
            preserve_default=False,
        ),
    ]
