# Generated by Django 3.1.6 on 2021-02-17 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_clanstatic_clan_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='player_battles',
            field=models.TextField(default=0, null=True, verbose_name='Всего боев'),
        ),
        migrations.AlterField(
            model_name='players',
            name='player_clan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.clanid'),
        ),
        migrations.AlterField(
            model_name='players',
            name='player_damage',
            field=models.TextField(default=0, null=True, verbose_name='Всего дамага'),
        ),
        migrations.AlterField(
            model_name='players',
            name='player_frags',
            field=models.TextField(default=0, null=True, verbose_name='Всего фрагов'),
        ),
        migrations.AlterField(
            model_name='players',
            name='player_name',
            field=models.TextField(null=True, verbose_name='Имя игрока'),
        ),
        migrations.AlterField(
            model_name='players',
            name='player_role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.clanrole'),
        ),
        migrations.AlterField(
            model_name='players',
            name='player_wgr',
            field=models.TextField(default=0, null=True, verbose_name='WGR'),
        ),
        migrations.AlterField(
            model_name='players',
            name='player_win',
            field=models.TextField(default=0, null=True, verbose_name='Всего побед'),
        ),
    ]
